### ISSUE TITLE
consider i have 1000 levels or quotes

### ISSUE THREAD

**Issue by Sreenivassreee** [JHBitencourt/beautiful_timelines#2]
consider i have 1000 levels or quotes first time i read 100 quotes.i close the app and then after that when i open i need to show 101 quotes..how can i do that my app again showing from 1...like candy crush app levels type...

**Comment by JHBitencourt** [comment]
Hey @Sreenivassreee.

I would say this is more a general Flutter question and not specific or related to this repository.

You could listen to ListView scroll with `ScrollController` and save the last level or quote that your user saw with sharedPrefs or other data storage.

Then when the user comes back you load this and jump to a `ListView` specific position using the same `ScrollController`.

**Comment by Sreenivassreee** [comment]
is it work like this in ( Success Timeline ) iam impressed with your work so i decided to use this Success Timeline in my new project, how can i implement in this... please suggest me easy way to do that..

**Comment by JHBitencourt** [comment]
I appreciate your support. 

But as I sad in my previous comment, `timeline_tile` is a simple tile that can be used with `ListView`. If you check the implementation from [success_timeline](https://github.com/JHBitencourt/beautiful_timelines/blob/master/lib/apps/success_timeline.dart) and combine it with `SharedPreferences` and `ScrollController` you can achieve what you desire. Search about this subjects.

For now I'm closing this issue.
